spring:
  profiles:
    active: ${SPRING_ACTIVE_PROFILE}
#    active: dev
  application:
    name: authService
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: ${CONFIG_SERVER_URI}
#      uri: http://localhost:8888
management:
  endpoints:
    web:
      exposure:
        include: refresh